import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kenya Controls Map",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title> <b>KENYA CONTROLS</b></title>
      <body className={inter.className}>
        <h1 className="h-8 bg-white text-black flex m-auto">KENYA CONTROLS</h1>
        {children}</body>
    </html>
  );
}
